### ISSUE TITLE
Write NER code for v1 synthetic data set

### ISSUE THREAD

**Issue by rockladyeagles** [vgcagle/DARC#10]
Process the v1 synthetic data set that Stephen creates (#8) using flair. Reject any text with != 2 organizational entities. For any text with == 2 organizational entities, replace the first org name with the string `__NE_FROM__` and the second org name with the string `__NE_TO__`. Work with @harmonyrose to determine a suitable format to give her for word embedding processing.

**Comment by rpersing** [comment]
Uploaded NER python script. It exists inside the ``synthetic`` directory created by @rockladyeagles.

**Comment by rpersing** [comment]
updated NER script to include labels
