### ISSUE TITLE
Get Bayne's code running

### ISSUE THREAD

**Issue by rockladyeagles** [vgcagle/DARC#25]
Bayne says:

> My status is that I have a general three step pipeline that results in an unsupervised set of general relations. ... Check out the gitlab if interested. I added a new project called LEARNv1. In there I cut out a lot of the fat crowding the other research git, and wrote some simple instructions in the Readme. I would love to see if you all could run it and give me your feedback.

**Comment by vgcagle** [comment]
Bayne also said:

Currently, I am using three pretrained models:
Flair sequence tagger trained on ontonotes
https://huggingface.co/flair/ner-english-ontonotes-fast?text=On+September+1st+George+Washington+won+1+dollar.
SpanBERT for coreference resolution
https://github.com/mandarjoshi90/coref
REBEL: Relation Extraction By End-to-end Language generation
https://github.com/Babelscape/rebel

Links to the respective papers are found in the repos.  Eventually I would like to fine-tune each of these models, but I have currently been focusing my time on accepting the results of the pretrained models, and attempting to reconcile inconsistencies between the models. One of the biggest issues I am currently looking into is how to unify the results of coreference resolution and named entity recognition.
