### ISSUE TITLE
Add README or otherwise clarify how to run fall 2022 code

### ISSUE THREAD

**Issue by rockladyeagles** [vgcagle/DARC#26]
For a new developer joining the project, what steps does he/she need to perform to get the Python code from 2022 running? (This includes answers to questions like what version of Python and its important packages are needed; which file(s) is the "main"; what command-line args are given to each "main" and what does each one do; etc.)

**Comment by rpersing** [comment]
added the README.md to the repo. It can be updated to be more verbose if necessary.
